### PR TITLE
Some New Organization :-)

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
All of the application code was inter-mixed with the config/deployment files.
This PR separates them out.
This also introduces a pattern to the frontend folder:
`ui/{components,routes}`, and gets rid of the containers folder.

I still need to test to make sure everything works (I have another project running, so I haven't been able to start this one, due to port conflict)

### CODE REVIEW

**Comment by abillingsley** [comment]
placing everything under a packages folder seems fine.  Justin and I debated if that should be done anyway to keep the root dir a little cleaner.

I am just starting on my first React app so opinions on the front end are welcome.  Looking at other DT projects it looked like we had settled around the following folder structure

* assets
   * images
   * styles
* components
* containers
* declarations
* infrastructure
* store
   * {domain concept}
      * actions
      * reducers

admittedly components and containers are just components.  Containers seemed to be redux connected components from what I have seen.  

Part of me likes the distinction between redux connected components and pure react components/functions but at the end of the day they are just components so I can see the case for mixing them together.

In George's apps I have not seen the `router` concept as a toplevel thing.  he seems to have an appRouter as a single file (in the project I have started working with I have taken a slightly different approach for routing).  So I am curious what the contents of your routes directory look like

**Comment by NullVoxPopuli** [comment]
Yeah, I've been meaning to talk to more people about what I've been doing on react project.
Personally, I don't really like / think it's a good idea to keep similar-typed things all isolated in frontend apps.

I think it's much more sustainable to group-by-feature than to group-by-type. Makes refactoring, and re-organizing large chunks of code pretty easy.


This is what was done with CME:

```
api/
├── jsonapi/
│   │
│   │   # decorator / 'container'
│   │   # - human-friendly abstraction to redux for querying the api, using the action creators 
│   │   #   defined in the api/ folder
│   ├── query.js
│   │
│   │   # default/templated action creators for getting basic endpoints going, including
│   │   # helpers for custom endpoints and such.
│   ├── base.js
│   │
│   │   # helpers for building / destructuring jsonapi documents, 
│   │   # because the format can be verbose for humans
│   ├── resource-builder.js
│
│   # each one of these is uses jsonapi/base to build the endpoints
│   # additonal state selectors are also defined in here.
│   # So, to get the current user, you'd import currentUserSelector from here and pass the state to it
├── users.js
├── roles.js
├── feature-toggles.js
│
│   # re-exports all the things
│   # defines custom actions/reducers that redux-bees (the jsonapi library) didn't support
│   # for example, we wanted to destroy all the data in the store when a user logged out.
│   #
│   # As a side note, having actions/reducers grouped together makes 
│   # for easy maintenance / discovery.
├── index.js

lib/
│
│   # includes stuff like:
│   #   getToken, deleteToken, isTokenExpired,
│   #   getDecodedJWT, login, isLoggedOut
├── auth0-helpers.js 
│
│   # additional abstractions using lodash functions
├── lodash-helpers.js

ui/
│
│    # global / shared components
├── components/
│    ├── authorization/
│         # decorator / 'container'
│      ├── requireRole 
│        #decorator / 'container'
│      ├── requireFeatureToggle 
│    ├── inputs/
│        # This is kind of a special component.. using the @query decorator and react-select
│        # it is only a 'container' component.
│        # but each time you want to have a 'role' select box, you can just use this, and @query
│        # will handle data fetching if it determines data needs to be fetched. 
│        # (I haven't actually tried having two of the same of these components on the screen
│        #  to see if redux-bees is smart enough to not make a second request)
│      ├── RoleSelect.js
│
│    # the idea behind routes is that the project structure should kinda match what is being rendered.
├── routes/
      # for example: localhost:8081/feature-toggles
    ├── FeatureToggles/
    ├── Roles/
    ├── Users/
        # react-router setup for list/show/edit, etc
        # should do nothing other than use <Route> and maybe some common layout html/css
      ├── index.js
 
         # This Component is used for creating users, which could be used by anything inside
         # the Users/ folder.
         # It's kind of "feature-local"
      ├── Create/
           # This project happened to use modals out the wazoo
         ├── Modal.js # renders the Form
           # makes the request, and sends an action up to modal for when to close 
           # (onSuccess or something)
         ├── Form.js 
      ├── List/
          # uses @query decorator, so this is kind of a 'container' component
        ├── index.js
         # example components
        ├── UserHeader/
        ├── UserTable/
          ├── index.js
          ├── UserTableRow

       ├── Show/
         ├── index.js          

```
Side Note: I was adding ├── and all those characters to make this easier to read.... and accidentally closed the tab... :-(


The project had a actions/reducers folders, but they didn't really need to be there, as there was no app-level state to maintain aside from the api-data (so, if we had started the project from scratch, there maybe would have just been index files combining all the reducers/sagas

For redux/store stuff, I think this'd be better (building off what you shared):

```
store/
  {domain concept}/
    index.js
    {specific domain concept 1}.js
    {specific domain concept 2}.js
```

there each (specific)domain concept defines the actions/action creators, reducers, and sagas all in one file. that way you're not hopping between slightly larger files to try to figure out how things interplay.




@dalinarkholin @abillingsley thoughts?

**Comment by abillingsley** [comment]
something Justin and I realized and a pattern I have been exploring for the video app is reusing the interfaces we define for the backend on the front end.  Let say you want to manage users. 

You probably have an api that can be called by web, mobile etc at `api/v1/users`.  This api returns JSON and maybe it conforms to json api spec.  The implementation of the list users route probably looks something like `listUsersService.exec(...)`.  **An** implementation ListUsersService may look like

```
// api/src/services/users/listUsers.ts

import { inject, injectable } from "inversify";
import { User, Identifiers, IListUserService, IRepository, ListUserRequest } from "~/core";

@injectable()
export default class ListUsers implements IListUserService {
  constructor(
    @inject(Identifiers.UserRepository) private userRepository: IRepository<User>,
  ) { }

  public async exec(request: ListUserRequest): Promise<User[]> {
    return this.userRepository.list({ limit: request.limit, offset: request.offset });
  }
}
```

the important thing here is that we have a repository for `IRepository<User>` that we are using for our backend service.  On the backend this may get users from a relational database, some other persistent store we manage, or potentially an external service via a rest api.  The important thing is that the concrete implementation of  `IRepository<User>` that we are using on the backend return a list of `User` entity 

Since we have the `IRepository<User>` interface on the front end we can provide **an** implementation of this interface that simply calls our `api/v1/users` route.

```
// web/src/infrastructure/users/userRepository.ts

import { User,  IFindOptions, IRepository } from "~/core";

export class UserRepository implements IRepository<User> {
  public list(options?: IFindOptions<User>): Promise<User[]> {
     //make http call to backend api and map JSON response to User entity
     //in a lot of the cases we have been able to use swagger to generate the http client etc which makes this implementation super easy
  }
}
```

I then realized that redux actions, in particular thunk actions are playing a role very similar to the "services" in the api layer.  With one minor difference these "services" dispatch events about the service lifecycle (started, done, failed)

```
//simple DI here, we could just as easily use inversify on the front end to wire up the dependencies 
// but that seemed heavy handed.  This gets us all the testability / swapability when things need to change 
const listUser = (userRepository: IRepository<User> = new UserRepository()): any => {
  return async (dispatch: Dispatch<any>, getState: any) => {
    dispatch(listUsersStarted());
    return userRepository.list()
      .then((users: User[]) => dispatch(listUsersSuccessful(users)))
      .catch((err: Error) => dispatch(listUsersFailure(err)););
  };
};
```

what I am really excited about with this is

1. we have the same level of flexibility and testability on the front end as we do on the backend 
2. just like the backend components are dependent on entities which abstract away how we got those entities.  No one but the repository needs to care that json api is used vs SOAP vs ...

the structure you have defined above I think makes a decent amount of sense and tends to parallel nicely with the intended structure of the toplevel `infrastructure` directory which is organized around domain concept.  I too think it is nice to organize files based on use case and to care less about "type".  

I think the biggest thing I would change is de-emphasizing the fact that the API is conforming to json api.  That way if for some reason v2 of the api needs to structure its responses differently OR instead of calling your api you need to call a different service.  You can simply provide an alternative implementation of the client side repository for the entities that require it and are therefore more loosely coupled to the data layer.  Since everything including the redux store depends on Core Entities making a large change to where or how entities are persisted/presented should have zero impact to the rest of the application since the application does not care where the entities came from or what they looked like on the wire

**Comment by NullVoxPopuli** [comment]
I get what you're saying. I think both of our goals can simultaneously be achieved.
For brevity, I'm not gonna keep typing here, since we'll likely both be in the office soonish/this week, So, I'd be happy to talk about things more in depth.

fwiw, I would have loved to use TS, Interfaces, and just... typed things in general on CME :-)

**Comment by dalinarkholin** [comment]
I just want to make sure I have been clear. Every App that I have built has used a structure that has worked best for that specific project. Since I am often hopping between Frontend only applications and a API/Frontend applications my implementations have differed.

Also, because of the steep learning curve of the Javascript world every project up to this point has been an improvement on the project before it. Leaving a lot of different implementations across our clients. I am not sure we are flattening out on this learning curve yet.

A lot of the apps I have done have been mobile only applications, which lend themselves toward a pretty flat structure.

That all beings said, I have very little opinion here. I would only ask the structure of the frontend would remain flexible enough to handle a wide range of implementations since the frontend is likely going to see the greatest amount of dependency change.

**Pull request merged**
